-- AlterTable
ALTER TABLE "order_reports" ALTER COLUMN "order_id" DROP NOT NULL,
ALTER COLUMN "order_date" DROP NOT NULL,
ALTER COLUMN "date_from" DROP NOT NULL,
ALTER COLUMN "format" DROP NOT NULL,
ALTER COLUMN "file_url" DROP NOT NULL,
ALTER COLUMN "status" DROP NOT NULL,
ALTER COLUMN "status" SET DATA TYPE TEXT,
ALTER COLUMN "report_type" DROP NOT NULL;

-- AlterTable
ALTER TABLE "transaction_reports" ALTER COLUMN "transaction_id" DROP NOT NULL,
ALTER COLUMN "transaction_date" DROP NOT NULL,
ALTER COLUMN "date_from" DROP NOT NULL,
ALTER COLUMN "format" DROP NOT NULL,
ALTER COLUMN "file_url" DROP NOT NULL,
ALTER COLUMN "status" DROP NOT NULL,
ALTER COLUMN "status" SET DATA TYPE TEXT,
ALTER COLUMN "report_type" DROP NOT NULL;
